apiVersion: v1
kind: Service
metadata:
  name: sbms-two-service
  labels:
    name: sbms-two-service-label
    app: sbms-two-service-app
spec:
  selector:
    name: sbms-two-deploy-pod-label
  #type: LoadBalancer
  #type: NodePort
  ports:
   - name: sbms-two-service-port
     port: 80
     targetPort: 9899
     protocol: TCP